### ISSUE TITLE
Simple.rs example uses Size instead of Size2 to create Shapes

### ISSUE THREAD

**Issue by tofraley** [walterpie/physme#6]
When I copy this example and run, I get a compilation error that Shape does not implement `From<Size>`.
Looking at the dim2 module, I see it does implement `From<Size2>`, which seems pretty similar.

Adding `use physme::dim2::Size2;` and then changing references from Size to Size2 seems to fix this.

**Comment by VaryDelicious** [comment]
Thank you for notifying me of this issue. Fixed, closing.

`use physme::dim2::Size2;` is also no longer necessary, as it is now re-exported in `physme::prelude2d`.
